name: Cypress Tests

on:
# runs tests every day at 4am
# schedule:
# - cron: '*/15 * * * *' # runs every 15th minute
#  - cron: '0 4 * * *'
 [ push ]

jobs:
  Run-Cypress-Test1:
    name: Cypress Test 1
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test1

  Run-Cypress-Test2:
    name: Cypress Test 2
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test2

  Run-Cypress-Test3:
    name: Cypress Test 3
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test3

  Run-Cypress-Test4:
    name: Cypress Test 4
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test4

  Run-Cypress-Test5:
    name: Cypress Test 5
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test5

  Run-Cypress-Test6:
    name: Cypress Test 6
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test6

  Run-Cypress-Test8:
    name: Cypress Test 8
    if: success() || failure()
    needs: [Run-Cypress-Test1]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test8

  Run-Cypress-Test9:
    name: Cypress Test 9
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test9

  Run-Cypress-Test10:
    name: Cypress Test 10
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test10

  # Store-snapshots:
  #   name: Store snapshots
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30
  #   needs: Run-Cypress-Test10
  #   container:
  #     image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
  #     options: --user 1001
  #   strategy:
  #     fail-fast: false
  #   steps:
  #     - uses: actions/upload-artifact@v1
  #       with:
  #         name: snapshot
  #         path: cypress/snapshots

  Run-Cypress-Test11:
    name: Cypress Test 11
    if: success() || failure()
    needs: [Run-Cypress-Test17]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test11

  Run-Cypress-Test12:
    name: Cypress Test 12
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test12

  Run-Cypress-Test13:
    name: Cypress Test 13
    if: success() || failure()
    needs: [Run-Cypress-Test1, Run-Cypress-Test14]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test13

  Run-Cypress-Test14:
    name: Cypress Test 14
    if: success() || failure()
    needs: [Run-Cypress-Test1, Run-Cypress-Test8]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test14

  Run-Cypress-Test15:
    name: Cypress Test 15
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test15

  Run-Cypress-Test16:
    name: Cypress Test 16
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test16


  Run-Cypress-Test17:
    name: Cypress Test 17
    if: success() || failure()
    needs: [Run-Cypress-Test13]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test17

  Run-Cypress-Test18:
    name: Cypress Test 18
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 60
  #  container:
   #   image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
  #    options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test18

  Run-Cypress-Test19:
    name: Cypress Test 19
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 60
  #  container:
   #   image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
  #    options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test19

  Run-Cypress-Test20:
    name: Cypress Test 20
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 60
  #  container:
  #    image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
   #   options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test20

  Run-Cypress-Test21:
    name: Cypress Test 21
    if: success() || failure()
    needs: [Run-Cypress-Test11]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test21

  Run-Cypress-Test22:
    name: Cypress Test 22
    if: success() || failure()
    needs: [Run-Cypress-Test21]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test22


  Run-Main-Script:
    name: Main Script
    if: success() || failure()
    needs: [Run-Cypress-Test1,Run-Cypress-Test2, Run-Cypress-Test3, Run-Cypress-Test4, Run-Cypress-Test5, Run-Cypress-Test6, Run-Cypress-Test8, Run-Cypress-Test9, Run-Cypress-Test10, Run-Cypress-Test11, Run-Cypress-Test12,Run-Cypress-Test13, Run-Cypress-Test14, Run-Cypress-Test15, Run-Cypress-Test16, Run-Cypress-Test17, Run-Cypress-Test18, Run-Cypress-Test19, Run-Cypress-Test20, Run-Cypress-Test21, Run-Cypress-Test22]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: node mainScript.js


env:
  #CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  CYPRESS_RECORD_KEY: a72a92d2-f84f-4c57-a807-ed2badaa0ba8
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
