name: Cypress Tests

on:
  # runs tests every day at 4am
  # schedule:
  # - cron: '*/15 * * * *' # runs every 15th minute
  #  - cron: '0 4 * * *'
  [ push ]

jobs:
  Run-Cypress-Test1-10-13-14:
    name: Cypress Test 1-10-13-14
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 120
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run clearGmail
      - name: Run Cypress Test
        run: npm run e2e-tests-1-10-13-14 || echo "Cypress failed with error code $?"
        shell: bash
        env:
          NODE_OPTIONS: --max-old-space-size=4096
      - name: Rerun Cypress Test if ECONNRESET
        if: ${{ failure() && contains(github.job.output, 'ECONNRESET') }}
        run: npm run e2e-tests-1-10-13-14






  Run-Clear-Gmail:
    name: Clear Gmail
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run clearGmail

  Create-log-directory:
    name: Create logs directory
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
      - run: mkdir $GITHUB_WORKSPACE/logs


env:
  #CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  CYPRESS_RECORD_KEY: 294f37fd-6ad6-4916-879f-4647b2b8057f
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
