name: Cypress Tests

on:
  # runs tests every day at 4am
  # schedule:
  # - cron: '*/15 * * * *' # runs every 15th minute
  #  - cron: '0 4 * * *'
  [ push ]

jobs:

  Run-Cypress-Test1:
    name: Cypress Test 1
    if: success() || failure()
    needs: [Run-Cypress-Test12]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run clearGmail
      - run: npm run e2e-test1
      - uses: actions/upload-artifact@v2
        with:
          name: data
          path: data.txt

  Run-Cypress-Test10:
    name: Cypress Test 10
    if: success() || failure()
    needs: [Run-Cypress-Test1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run clearGmail
      - uses: actions/download-artifact@v2
        with:
          name: data
          # Copy the data file to the current directory
      - name: Copy data file
      - run: cp ${{ github.workspace }}/data.txt
      - run: npm run e2e-test10

  Run-Clear-Gmail:
    name: Clear Gmail
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run clearGmail




  # Store-snapshots:
  #   name: Store snapshots
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30
  #   needs: Run-Cypress-Test10
  #   container:
  #     image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
  #     options: --user 1001
  #   strategy:
  #     fail-fast: false
  #   steps:
  #     - uses: actions/upload-artifact@v1
  #       with:
  #         name: snapshot
  #         path: cypress/snapshots



  Run-Cypress-Test12:
    name: Cypress Test 12
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test12

  Run-Cypress-Test13:
    name: Cypress Test 13
    if: success() || failure()
    needs: [Run-Cypress-Test1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run clearGmail
      - run: npm run e2e-test13

  Run-Cypress-Test14:
    name: Cypress Test 14
    if: success() || failure()
    needs: [Run-Cypress-Test1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run clearGmail
      - run: npm run e2e-test14





























env:
  #CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  CYPRESS_RECORD_KEY: 05fe6f92-a82c-4c56-a545-b113301347be
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
