name: Cypress Tests

on:
  # runs tests every day at 4am
  #schedule:
  # - cron: '*/15 * * * *' # runs every 15th minute
  #  - cron: '0 4 * * *'
  [ push ]

jobs:

  Run-Cypress-Test1:
    name: Cypress Test 1
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - run: npm i
      - run: npm run e2e-test1

  Fetch-email-1:
    name: Fetch email 1
    if: success() || failure()
    needs: [Run-Cypress-Test1]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - run: npm i
      - run: npm run email1

  Run-Cypress-Test8:
    name: Cypress Test 8
    if: success() || failure()
    needs: [Run-Cypress-Test1]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    #  container:
    #    image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
    #    options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm i
      - run: npm run e2e-test8

  Fetch-email-8:
    name: Fetch email 8
    if: success()
    needs: [Run-Cypress-Test8 ]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    # container:
    #   image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
    #   options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - run: npm i
      - run: npm run email8


env:
  #CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  CYPRESS_RECORD_KEY: 765baaa8-7f06-448c-ae3b-155bc7077551
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
