name: Cypress Tests

on:
# runs tests every day at 4am
# schedule:
# - cron: '*/15 * * * *' # runs every 15th minute
#  - cron: '0 4 * * *'
 [ push ]

jobs:
  Run-Cypress-Test2-1:
    name: Cypress Test 10
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test10

  Run-Cypress-Test2-2:
    name: Cypress Test 10
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test10

  Run-Cypress-Test2-3:
    name: Cypress Test 10
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test10

  Run-Cypress-Test2-4:
    name: Cypress Test 10
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test10

  Run-Cypress-Test2-5:
    name: Cypress Test 10
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test10

  Run-Cypress-Test2-6:
    name: Cypress Test 10
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test10

  Run-Cypress-Test2-7:
    name: Cypress Test 10
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test10

  Run-Cypress-Test2-8:
    name: Cypress Test 10
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test10

  Run-Cypress-Test2-9:
    name: Cypress Test 10
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test10

  Run-Cypress-Test2-10:
    name: Cypress Test 10
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run e2e-test10









env:
  #CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  CYPRESS_RECORD_KEY: fbcb11db-f2de-4d9a-8e4d-f90d60d6902c
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
