name: Cypress Tests
on:
  # schedule:
  #  - cron: '0 4 * * *'
  [ push ]

permissions: write-all

env:
  #CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}


jobs:

  clear-previous-reports:
    runs-on: ubuntu-latest
    timeout-minutes: 250
    if: always()
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: remove previous reports
        run: |
          mkdir emptyFolder
      - name: Deploy blank report folder temp reports branch
        uses: peaceiris/actions-gh-pages@v2
        with:
          keepFiles: false
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: emptyFolder

  Run-Clear-Gmail:
    name: Clear Gmail
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run clearGmail



  Run-Cypress-Test9:
    name: Cypress Test 9
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 40
   #needs: [ Run-Cypress-Test1 ]
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - uses: nick-invision/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: npm run e2e-test9

      #  - run: npm run e2e-test22
      - run: |
          mkdir report/S3_bucket
          mv S3_bucket/* report/S3_bucket
          mv mainScript.js report

      - name: Increase Git timeout
        run: git config --global http.postBuffer 524288000

      - name: Deploy report to temp-reports branch
        if: always()
        continue-on-error: true
        uses: peaceiris/actions-gh-pages@v2
        with:
          keepFiles: true
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: report





  merge-and-deploy-final-report:
    runs-on: ubuntu-latest
    timeout-minutes: 250
    continue-on-error: true
    needs: [Run-Cypress-Test6]
    if: always()
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Install dependencies
        run: |
          git config --global http.postBuffer 157286400
          npm init --yes
          npm i allure-commandline --save-dev
          npm i aws-sdk --save-dev
          npm i path --save-dev
          npm i fs --save-dev
          mkdir allure-results
          #  mkdir allure-results-failed
          
          
          if [ -d "allure-results-1" ]; then
          mv allure-results-1/* allure-results
          fi
          if [ -d "allure-results-2" ]; then
          mv allure-results-2/* allure-results
          fi
          if [ -d "allure-results-3" ]; then
          mv allure-results-3/* allure-results
          fi
          if [ -d "allure-results-4" ]; then
          mv allure-results-4/* allure-results
          fi
          if [ -d "allure-results-5" ]; then
          mv allure-results-5/* allure-results
          fi
          if [ -d "allure-results-6" ]; then
          mv allure-results-6/* allure-results
          fi
          if [ -d "allure-results-8" ]; then
          mv allure-results-8/* allure-results
          fi
          if [ -d "allure-results-9" ]; then
          mv allure-results-9/* allure-results
          fi
          if [ -d "allure-results-10" ]; then
          mv allure-results-10/* allure-results
          fi
          if [ -d "allure-results-11" ]; then
          mv allure-results-11/* allure-results
          fi
          if [ -d "allure-results-12" ]; then
          mv allure-results-12/* allure-results
          fi
          if [ -d "allure-results-13" ]; then
          mv allure-results-13/* allure-results
          fi
          if [ -d "allure-results-15" ]; then
          mv allure-results-15/* allure-results
          fi
          if [ -d "allure-results-16" ]; then
          mv allure-results-16/* allure-results
          fi
          if [ -d "allure-results-17" ]; then
          mv allure-results-17/* allure-results
          fi
          if [ -d "allure-results-17.1" ]; then
          mv allure-results-17.1/* allure-results
          fi
          if [ -d "allure-results-17.2" ]; then
          mv allure-results-17.2/* allure-results
          fi
          if [ -d "allure-results-18" ]; then
          mv allure-results-18/* allure-results
          fi
          if [ -d "allure-results-19" ]; then
          mv allure-results-19/* allure-results
          fi
          if [ -d "allure-results-20" ]; then
          mv allure-results-20/* allure-results
          fi
          if [ -d "allure-results-21" ]; then
          mv allure-results-21/* allure-results
          fi
          if [ -d "allure-results-22" ]; then
          mv allure-results-22/* allure-results
          fi
          if [ -d "allure-results-23" ]; then
          mv allure-results-23/* allure-results
          fi

      - name: Set up environment variable
        id: set_date
        run: echo "NOW=$(date +'%B_%d')" >> $GITHUB_ENV

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate Allure Report for all tests
        if: always()
        run: |
          node_modules/allure-commandline/dist/bin/allure generate allure-results -o report/all-tests

      - name: Deploy all tests report to external repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.EXTERNAL_REPOSITORY_PERSONAL_ACCESS_TOKEN }}
          NOW: ${{ env.NOW }}
        with:
          source-directory: report/all-tests
          destination-github-username: 'Nucleus-Reports'
          destination-repository-name: 'report_${{ env.NOW }}'
          user-email: 'qa-user1'
          target-branch: "main"

  upload-artifacts-to-S3:
    name: Upload artifacts to S3
    if: success() || failure()
    runs-on: ubuntu-latest
    timeout-minutes: 40
    needs: [ merge-and-deploy-final-report ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: |
          npm i
          node mainScript.js
  

